export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FINISHED = 'LOGIN_FINISHED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FINISHED = 'REGISTER_FINISHED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_FINISHED = 'UPDATE_FINISHED'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const LOG_OUT = 'LOG_OUT'
export const LOG_IN = 'LOG_IN'

export const ALL_USER_REQUEST = 'ALL_USER_REQUEST'
export const ALL_USER_FINISHED = 'ALL_USER_FINISHED'
export const ALL_USER_FAILED = 'ALL_USER_FAILED'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const CREATE_FINISHED = 'CREATE_FINISHED'
export const CREATE_FAILED = 'CREATE_FAILED'